config/routes.rb
Rails.application.routes.draw do
  resources :estanteevs
  get 'livros/index'

  root 'livros#index'

  resources :livros
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/estanteev.rb
class Estanteev < ApplicationRecord
end

app/models/livro.rb
class Livro < ApplicationRecord
    
    belongs_to :estanteev

	has_attached_file :capa, styles:{large: "600x600", medium: "300x300", thumb: "90x150#"}
	validates_attachment_content_type :capa, content_type: /\Aimage\/.*\z/

	validates_attachment_content_type :capa, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/estanteevs_controller.rb
class EstanteevsController < ApplicationController
  before_action :set_estanteev, only: [:show, :edit, :update, :destroy]

  # GET /estanteevs
  # GET /estanteevs.json
  def index
    @estanteevs = Estanteev.all
  end

  # GET /estanteevs/1
  # GET /estanteevs/1.json
  def show
  end

  # GET /estanteevs/new
  def new
    @estanteev = Estanteev.new
  end

  # GET /estanteevs/1/edit
  def edit
  end

  # POST /estanteevs
  # POST /estanteevs.json
  def create
    @estanteev = Estanteev.new(estanteev_params)

    respond_to do |format|
      if @estanteev.save
        format.html { redirect_to @estanteev, notice: 'Estanteev was successfully created.' }
        format.json { render :show, status: :created, location: @estanteev }
      else
        format.html { render :new }
        format.json { render json: @estanteev.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estanteevs/1
  # PATCH/PUT /estanteevs/1.json
  def update
    respond_to do |format|
      if @estanteev.update(estanteev_params)
        format.html { redirect_to @estanteev, notice: 'Estanteev was successfully updated.' }
        format.json { render :show, status: :ok, location: @estanteev }
      else
        format.html { render :edit }
        format.json { render json: @estanteev.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estanteevs/1
  # DELETE /estanteevs/1.json
  def destroy
    @estanteev.destroy
    respond_to do |format|
      format.html { redirect_to estanteevs_url, notice: 'Estanteev was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estanteev
      @estanteev = Estanteev.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estanteev_params
      params.require(:estanteev).permit(:nome)
    end
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController

  def index

  	@livros = Livro.all

  end

  def show

  	@livro = Livro.find(params[:id])
  	
  end

  def new

  	@livro = Livro.new
    @estanteevs = Estanteev.all

  end

  def create

  	@livro = Livro.new(livros_params)

  	if @livro.save
     redirect_to livros_path
    else
     render 'new'
    end  
  	
  end

  def edit

  	@livro = Livro.find(params[:id])
    @estanteevs = Estanteev.all
  	
  end

  def update

  	@livro = Livro.find(params[:id])
  	@livro.update(livros_params)
  	redirect_to livros_path
  	
  end

  def destroy

  	@livro = Livro.find(params[:id])
  	@livro.destroy
  	redirect_to livros_path
  	
  end

  private
   def livros_params

   	 params.require(:livro).permit(:titulo, :autor, :sinopse, :estante, :capa, :estanteev_id)
   	
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estanteevs_helper.rb
module EstanteevsHelper
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/views/estanteevs/_form.html.erb
<%= form_with(model: estanteev, local: true) do |form| %>
  <% if estanteev.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estanteev.errors.count, "error") %> prohibited this estanteev from being saved:</h2>

      <ul>
      <% estanteev.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :estanteev_nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/estanteevs/edit.html.erb
<h1>Editing Estanteev</h1>

<%= render 'form', estanteev: @estanteev %>

<%= link_to 'Show', @estanteev %> |
<%= link_to 'Back', estanteevs_path %>

app/views/estanteevs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estanteevs</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estanteevs.each do |estanteev| %>
      <tr>
        <td><%= estanteev.nome %></td>
        <td><%= link_to 'Show', estanteev %></td>
        <td><%= link_to 'Edit', edit_estanteev_path(estanteev) %></td>
        <td><%= link_to 'Destroy', estanteev, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estanteev', new_estanteev_path %>

app/views/estanteevs/new.html.erb
<h1>New Estanteev</h1>

<%= render 'form', estanteev: @estanteev %>

<%= link_to 'Back', estanteevs_path %>

app/views/estanteevs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @estanteev.nome %>
</p>

<%= link_to 'Edit', edit_estanteev_path(@estanteev) %> |
<%= link_to 'Back', estanteevs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LivrosEV</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/livros/_form.html.erb
<div class="container">

<%= form_for @livro, html:{multipart: true} do |f| %>
 
  <% if @livro.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@livro.errors.count, "error") %> 
          O Livro não pode ser adicionado
      </h2>
      <ul>
        <% @livro.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :Titulo %><br>
    <%= f.text_field :titulo, class:"form-control" %>
  </p>

  <p>
    <%= f.label :Autor %><br>
    <%= f.text_field :autor, class:"form-control" %>
  </p>

  <p>
    <%= f.label :Capa %><br>
    <%= f.file_field :capa, class:"form-control" %>
  </p>

  <p>
    <%= f.label :Sinopse %><br>
    <%= f.text_area :sinopse, class:"form-control" %>
  </p>
 
  <div class="form-group">
    <%= f.label :Estante %>
    <%= f.collection_select :estanteev_id, @estanteevs, :id, :nome, {}, class: "form-control" %>
</div>
 
  <p>
    <%= f.submit :Salvar, class:"btn btn-success" %>
  </p>
 
<% end %>

</div>

app/views/livros/edit.html.erb
<%= nav_bar brand: "Editando"  %>

<%= render 'form' %>

<div class="container" ><%= link_to "Voltar", livros_path %></div>

app/views/livros/index.html.erb
<%= nav_bar brand: "Livros" %>

<div class="container">
 
<table class="table table-bordered">
  <tr>
    <th>Título</th>
    <th>Autor</th>
    <th>Sinopse</th>
    <th>Capa</th>
    <th>Estante</th>
  </tr>
 
  <% @livros.each do |livro| %>
    <tr>
      <td><%= livro.titulo %></td>
      <td><%= livro.autor %></td>
      <td><%= livro.sinopse %></td>
      <td><%= image_tag livro.capa.url(:thumb) %></td>
      <td><%= livro.estanteev.nome %></td>
      <td><%= link_to 'Editar', edit_livro_path(livro), class: "btn btn-warning" %></td>
      <td><%= link_to 'Remover', livro_path(livro), class: "btn btn-danger", method: :delete,
                                                       data:{confirm: "Tem certeza"} %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Adicionar Livro", new_livro_path, class:"btn btn-success" %>

</div>

app/views/livros/new.html.erb
<%= nav_bar brand: "Novo Livro"  %>

<%= render 'form' %>

<div class="container" ><%= link_to "Voltar", livros_path %></div>